source 'https://github.com/CocoaPods/Specs.git'
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CollectionViewDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CollectionViewDemo

pod 'SDWebImage', '~> 4.0'
pod 'Kingfisher', '~> 4.7.0'
end
